# Generated by Django 4.2.20 on 2025-04-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за ночь')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID оплаты')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rental.rentalproperty', verbose_name='Объект аренды')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rental.rentalproperty', verbose_name='Объект')),
            ],
        ),
    ]
