# Generated by Django 4.2.20 on 2025-04-30 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='properties/main/')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['price_per_night'], name='rental_rent_price_p_6919ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='rental.rentalproperty')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField(default=1, help_text='Guests aged 13 and above')),
                ('children', models.PositiveIntegerField(default=0, help_text='Guests aged 3 to 12')),
                ('infants', models.PositiveIntegerField(default=0, help_text='Guests aged up to 2 (crib/high chair)')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('add_bed', models.BooleanField(default=False, help_text='Additional bed (€50/night)')),
                ('high_chair', models.BooleanField(default=False, help_text='High chair (€10 flat)')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=8)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rental_property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rental.rentalproperty', verbose_name='property')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('rental_property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rental.rentalproperty', verbose_name='property')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('check_out__gt', models.F('check_in'))), name='check_out_after_check_in'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['rental_property', 'date'], name='rental_avai_propert_1e4b86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('rental_property', 'date')},
        ),
    ]
