# Generated by Django 4.2.20 on 2025-04-30 19:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Уборка (включается в итоговую сумму брони)', max_digits=8),
        ),
    ]
