# Generated by Django 4.2.20 on 2025-04-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20250426_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalproperty',
            options={'verbose_name': 'Вилла', 'verbose_name_plural': 'Виллы'},
        ),
        migrations.RemoveField(
            model_name='rentalproperty',
            name='address',
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
