# Generated by Django 4.2.20 on 2025-04-29 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_rentalproperty_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalproperty',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental.rentalproperty')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_gallery/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='rental.rentalproperty')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
            },
        ),
    ]
